[Preferences]
WebUI\BypassAuthentication=true
Category\path\Default=/downloads
Category\savePath\Default=/downloads
Category\path\Films=/downloads/Films
Category\savePath\Films=/downloads/Films
Category\path\Games=/downloads/Games
Category\savePath\Games=/downloads/Games
Category\path\Others=/downloads/Others
Category\savePath\Others=/downloads/Others
Category\path\Serials=/downloads/Serials
Category\savePath\Serials=/downloads/Serials
Bittorrent\SchedulerEnabled=true
Bittorrent\SchedulerDays=96
Bittorrent\SchedulerUpload=10
Bittorrent\SchedulerDownload=0
Bittorrent\SchedulerStartHour=0
Bittorrent\SchedulerStartMin=0
Bittorrent\SchedulerEndHour=23
Bittorrent\SchedulerEndMin=59
Bittorrent\MaxRatioEnabled=true
Bittorrent\MaxRatio=1
Bittorrent\MaxRatioAction=1
RunExternalProgramEnabled=true
RunExternalProgramOnTorrentAdded=true
RunExternalProgramOnTorrentAddedCommand=curl -X POST "http://localhost:6060/api/start" -H "Content-Type: text/plain" -d "%I"
RunExternalProgramOnTorrentFinished=true
RunExternalProgramOnTorrentFinishedCommand=curl -X POST "http://localhost:6060/api/complete" -H "Content-Type: text/plain" -d "%I"
