name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  call-deploy:
    uses: leoserverteam/DevOpsTemplates/.github/workflows/deploy-with-configs.yml@main
    with:
      project_name: "QbiTorrent"
      config_paths: config

  call-nginx:
    uses: leoserverteam/DevOpsTemplates/.github/workflows/deploynginx.yml@main
